### PR TITLE
add max memory for vm configuration

### PR DESCRIPTION
**Pull request by rosbeef**
to set max memory usage

## Problem

on small memory SBC default java VM memory alocation is too much "3072mb" 
this result in jvb and jicofo fails to start

## Solution

set VIDEOBRIDGE_MAX_MEMORY and JICOFO_MAX_MEMORY in respective config file depends on estimated max user using bridge at a time

## PR Status

- [x] Code finished and ready to be reviewed/tested
  - [x] install (manifest + script)
  - [x] update (script)
  - [x] restore (script)
  - [x] config (toml + script)
- [x] The fix/enhancement were manually tested (if applicable)
  - [x] install (manifest + script)
  - [x] update (script)
  - [x] restore (script)
  - [x] config (toml + script)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rosbeef** [comment]
done
tested working

**Comment by rosbeef** [comment]
!testme

**Comment by rosbeef** [comment]
! only install script is done

**Comment by yalh76** [comment]
Great work.
As you ask for the `maxmembers` during install, wouldn't it be better to also ask for the `maxmembers` in the config panel ? to have more consistent questions ?
And having a personal helper in `_common.sh` to calculate the `max_memory` ? maybe able to check the actual memory size and adapt the `maxmembers`

**Comment by rosbeef** [comment]
maybe you have right and only max memory is better, admin should know how much memory he have on his server

**Comment by rosbeef** [comment]
maybe you can help me
config fail but doesn't indicates were is the error:
https://paste.yunohost.org/raw/sopadaduqe

**Comment by yalh76** [comment]
I haven't used config panel fro now, but all I see in your log is: L7 `error: Unknown service ''`
but I don't know what service, it's looking for ...

**Comment by rosbeef** [comment]
@yalh76 All done!
Can be tested even in your config if you want to free memory ;)
now let me understand why ports appear as not open in dagnosis

**Comment by yalh76** [comment]
> now let me understand why ports appear as not open in dagnosis

the port is open but nothing is responding until first meeting is launched ^^

**Comment by rosbeef** [comment]
ok, how to merge my modification in testing now ? 
sorry i'm noob in contributing :P

**Comment by yalh76** [comment]
I will check if there is a way to test the config panel

**Comment by yalh76** [comment]
I've made two draft PR:
- https://github.com/rosbeef/jitsi_ynh/pull/1 : to have a more simple process to define the max memory
- https://github.com/rosbeef/jitsi_ynh/pull/2 : to let user set the maximum users, maximum handled users is calculated from the available memory ...

Let me know what you think of that.

**Comment by rosbeef** [comment]
I think max memory is the best way :
1rst configurate max memory is better because we are talking about memory.
2nd Maybe max users could be needed for a parameter that i have not the knowlege.
3rd talking about users to configure memory should be source of misundertanding because some admin maybe want to host lots of simultaneous users but don't know that will require all of his memory.

after, in other PR we could inform that 10% of available memory should permit to host meeting for N simultaneous users (all meetings included).

**Comment by rosbeef** [comment]
i don't know if i did well to merge.
it was like a back flip in forks, I'm a bit lost
now what to do ?

**Comment by yalh76** [comment]
> i don't know if i did well to merge. it was like a back flip in forks, I'm a bit lost now what to do ?

merged in testing and in master after a full package_check

**Comment by tio-trom** [comment]
How will this affect current Jitsi installations? I have plenty of RAM and I'd like it to use as much as possible. Is this new push a limitation? If so how to remove it or increase it? Thanks!

**Comment by rosbeef** [comment]
Yes
You can increase memory in config panel. Default is 75mb,
One simultaneous user un the instance use around 1,5 mb ram .

**Comment by tio-trom** [comment]
Awesome. So easy! Thanks a lot!

**Pull request merged**
