### PR TITLE
[WIP] Fix video V2

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Jitsi doesn't work*

## Solution
- *Still doesn't work, but I tried to upgrade the package with the latest version*

I can create a room and join it with only 1 person. (Which is very limited for Jisti)

Here some logs:

When I create and join a room:
- [metronome.log](https://paste.yunohost.org/tekomacuzi.nginx)
- [metronome.dbg](https://paste.yunohost.org/usijidelam.lua)
- metronome.err: empty
- [jitsi-jicofo.log](https://paste.yunohost.org/qekatotibu.vbs)
- [jitsi-videobridge](https://paste.yunohost.org/eqedoqinaq.css)

When another user tries to join the room:
- [metronome.log](https://paste.yunohost.org/wukomabozi.nginx)
- [metronome.dbg](https://paste.yunohost.org/asehexeyut.lua)
- metronome.err: empty
- [jitsi-jicofo.log](https://paste.yunohost.org/owatiyuhuz.sql)
- [jitsi-videobridge](https://paste.yunohost.org/ajiyiwapew.css)

When the second user comes, I have some errors in the [browser console](https://paste.yunohost.org/aqacupasas.swift)

That's a lot of logs, and I don't have the knowledge to understand them and find the error.

Sorry for the noise, bug ping @maranda if you have any clues about this

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/jitsi_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by maranda** [comment]
@kay0u is the videobridge running? That error is related to the video bridge not running apparently.

**Comment by kay0u** [comment]
Yes, and in the logs you can see some health check. But it's maybe not well configured...

**Comment by maranda** [comment]
Yeah possibly, do you have the configuration handy? I think a hint of the culprit might be those "owner left" messages. I'll see if I can catch something out of it.

**Comment by maranda** [comment]
Okay I found two issues, which could track down the issue here, which I believe are solidly related to bridge configuration and SSL configuration:

https://community.jitsi.org/t/jitsi-videobridge2-failed-to-select-initial-bridge-for-participantregion-null/24516/8
and
https://community.jitsi.org/t/saslerror-using-scram-sha-1-not-authorized-on-debian-buster-system-with-existing-prosody/26775

Apparently the mess could be caused by a problem with the reverse proxy configuration of NGINX.

**Comment by maranda** [comment]
There's also an issue with the muc components configuration you're using Prosody config, I just noticed it now sorry:
See https://github.com/maranda/metronome/issues/528#issuecomment-751832108

**Comment by kay0u** [comment]
Thank you for the tips, here the log of jicofo: https://paste.yunohost.org/jujehepire.sql

Especially when I create a new room and someone else join the room: https://paste.yunohost.org/eqiwunocum.vbs

> Selected initial bridge Bridge[jid=jvbbrewery@internal.auth.kayou.ynh.fr/9f50c873-a38d-4c7c-ade7-6f44841a8428, relayId=null, region=null, stress=0.00] with stress=0.0 for participantRegion=null
Jicofo 2020-12-28 20:33:48.137 INFO: [30] org.jitsi.impl.protocol.xmpp.colibri.OperationSetColibriConferenceImpl.log() Conference created: org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl@3a8290b9

Looks like it's way better and videobridge is selected. But I still have this error in browser:

> CONFERENCE FAILED: conference.focusLeft

/o\

**Comment by maranda** [comment]
@kay0u you missed a bit for the lobby it looks

```
Component "lobby.__DOMAIN__" "muc"
    storage = "cache"
    restrict_room_creation = true
    allow_anonymous_creation = true
    instant_room_on_creation = true
    room_default_config = { whois = "anyone" }
```

**Comment by maranda** [comment]
@kay0u you missed a bit for the lobby it looks

```
Component "lobby.__DOMAIN__" "muc"
    storage = "cache"
    restrict_room_creation = true
    instant_room_on_creation = true
    room_default_config = { whois = "anyone" }
```

**Comment by kay0u** [comment]
:+1: done (Still the same errors, but thanks for your review!)

**Comment by maranda** [comment]
@kay0u any news? Also can you try with DEBUG level in Jitsi Videobridge logging enabled? I see only INFO and WARNING and a few pieces are missing I feel.

**Comment by maranda** [comment]
https://github.com/YunoHost-Apps/jitsi_ynh/pull/55/commits/920d50f77642ce03e598c7881e86f93d1be7e97d#diff-debaaf2dda60b0c8dd2dc1f2bdd7ab0da7d380cc7fdee57c8f1735efc8bda3f1R8 also you seem to be using mod_turncredentials from Prosody modules instead of mod_extdisco, but the configuration is wrong there's no turncredentials option that can be passed as a table.

Why aren't you using mod_extdisco instead?

**Comment by maranda** [comment]
I can't setup a testing environment atm, so I'll have to rely on your findings but there seems to be all TURN/STUN configuration missing there.

**Pull request closed without merging**
