### PR TITLE
Integrate coturn

### LINKED ISSUE #10: no video and audio, when connect two users
When connecting a second user, there is no audio and video(black screen) from the other user - you just can see yourself.

used: Firefox 68, latest yunohost

With https://meet.jit.si/ it works, so it has nothing to do with firefox.
I checked the ports TCP/4443 and UDP/10000 and 4443 is open, 10000 is closed. I did not configure anything, but 4443 is already open.

I contacted my vServer provider and he tells me, that it is just me and my config, who can block ports. 
I do not think, that an extra DNS SRV entry is necessary. jit.si has no SRV entry in their dns config. (https://viewdns.info/dnsrecord/?domain=jit.si)
yunohost firewall says port 10000 is open.

Does this help? https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#running-behind-nat

### LINKED ISSUE #29: Limit of 2 connections
Hey,

I have a fresh updated yunohost. A few days ago I have added Jitsi Meet. With up to two participants it works great. But all further participants are getting a user/password dialog. Of course I have noch setup a password. My Meet instance should be open for all, no user limitations. 

These files could not be loaded (Error 404):
/ynh_overlay.css
/custom_overlay.css
/custom_overlay.css
/custom_portal.js

I see no further errors. 

Whats going wrong? 

Thanks for your help. 

Cheers, derMicha

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Fix #29*
- *Fix #10*

## Solution
- *Integrate coturn*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/jitsi_ynh%20PR34%20(yalh76)/)

### CODE REVIEW

**Comment by scharc** [comment]
I was looking in the coturn server for nextcloud talk and was thinking maybe we can split it in a helper for ynh instead of implement it for each app separately. 
Apps that can use the same coturn server:
* synapse
* nextcloud talk
* jitsi

**Comment by Aeris1One** [comment]
Is this working ? Can we use this branch to make two-or-more-users calls ?

**Comment by yalh76** [comment]
> 
> 
> Is this working ? Can we use this branch to make two-or-more-users calls ?
> 
> Je me suis permis de lancer un test sur le CI, évidement y'avait deux autres builds en file d'attente 😑
> 
> [](https://ci-apps-dev.yunohost.org/jenkins/job/jitsi_ynh%20coturn%20(aeris)/)

It can be installed, remove, etc... But I'm not sure it's working better than the master branch.... I made some test but it was between computers from the same network....

**Comment by Aeris1One** [comment]
Et a cause du confinement t'a pas tellement moyen d'utiliser plusieurs réseaux :/

**Comment by yalh76** [comment]
> 
> 
> Et a cause du confinement y'a pas tellement moyen d'utiliser plusieurs réseaux :/

Yes indeed, So if someone has time to install the coturn branch and make some test, would be helpfull :)

**Comment by yalh76** [comment]
> 
> 
> I was looking in the coturn server for nextcloud talk and was thinking maybe we can split it in a helper for ynh instead of implement it for each app separately.
> Apps that can use the same coturn server:
> 
>     * synapse
> 
>     * nextcloud talk
> 
>     * jitsi

Seems that only synapse is using coturn and just tried with jitsi without being sure of what I made.

Feel free to make a PR for the helper, I could review it for the few things I've learn about coturn

**Pull request merged**
